package telegram

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"sync/atomic"
)

// QueryID identifies a request sent through the asynchronous TDLib JSON
// interface.
//
// The value is serialized into the request's @extra field. TDLib copies
// the same value into the corresponding response.
type QueryID string

// queryNamespace is prepended to every QueryID generated by this
// package. The session pump uses it to distinguish telecli responses
// from application updates that happen to carry an unrelated @extra.
const queryNamespace = "telecli:"

var (
	// ErrQueryInvalidRequest is returned when a request is empty, is not
	// a JSON object, or already contains an @extra field.
	ErrQueryInvalidRequest = errors.New("telegram query: invalid request")

	// ErrQuerySessionClosed is returned when the session pump exits
	// before a pending response is received.
	ErrQuerySessionClosed = errors.New("telegram query: session closed")

	// ErrQueryResponseChannelClosed is returned when a registered query
	// response channel closes without delivering a response.
	ErrQueryResponseChannelClosed = errors.New("telegram query: response channel closed")

	// ErrTDLibResponse indicates that TDLib returned an object with
	// @type "error".
	ErrTDLibResponse = errors.New("telegram query: TDLib error response")
)

// TDLibError is the typed representation of a TDLib error response.
type TDLibError struct {
	Code    int
	Message string
	Extra   QueryID
	Raw     RawMessage
}

// Error implements error.
func (e *TDLibError) Error() string {
	if e == nil {
		return ErrTDLibResponse.Error()
	}
	if e.Message == "" {
		return fmt.Sprintf("%s: code=%d", ErrTDLibResponse, e.Code)
	}
	return fmt.Sprintf("%s: code=%d message=%q",
		ErrTDLibResponse, e.Code, e.Message)
}

// Unwrap makes TDLibError compatible with errors.Is.
func (e *TDLibError) Unwrap() error {
	return ErrTDLibResponse
}

// queryEnvelope carries the metadata used by the session pump to route
// a response.
type queryEnvelope struct {
	Type  string          `json:"@type"`
	Extra json.RawMessage `json:"@extra"`
}

// tdlibErrorEnvelope mirrors the fields returned by TDLib error objects.
type tdlibErrorEnvelope struct {
	Type    string          `json:"@type"`
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Extra   json.RawMessage `json:"@extra"`
}

// pendingQuery receives exactly one matching response.
//
// The channel is buffered so the session pump never waits for the
// caller to be scheduled after the response has arrived.
type pendingQuery struct {
	response chan queryResult
}

// queryResult is the internal result delivered by the session pump.
type queryResult struct {
	raw RawMessage
	err error
}

// querySequence is process-wide and is the only source of telecli @extra
// identifiers. Every request in the process is numbered here, whoever
// sends it: the authorization coordinator, a linkage probe and the session
// pump all ask newQueryID.
//
// One counter is the whole point. Two counters would hand out the same
// identifier twice, and TDLib answers a request by its identifier alone,
// so the second requester of an identifier would receive the first
// requester's answer.
var querySequence atomic.Uint64

// newQueryID returns a unique query identifier for one logical client.
//
// It is the single mint for @extra. Anything that sends a request this
// package will answer must come through here.
func newQueryID(clientID int) QueryID {
	sequence := querySequence.Add(1)
	return QueryID(
		queryNamespace +
			strconv.Itoa(clientID) + ":" +
			strconv.FormatUint(sequence, 10),
	)
}

// isTelecliQueryID reports whether id belongs to this package's
// namespace.
func isTelecliQueryID(id QueryID) bool {
	return strings.HasPrefix(string(id), queryNamespace)
}

// withQueryID copies a JSON request object and adds @extra.
//
// The caller's byte slice is never modified. Requests that already
// contain @extra are rejected: overwriting the field would silently
// destroy correlation metadata owned by another component.
func withQueryID(request RawMessage, queryID QueryID) (RawMessage, error) {
	if len(request) == 0 {
		return nil, ErrQueryInvalidRequest
	}
	if queryID == "" {
		return nil, fmt.Errorf("%w: empty query ID", ErrQueryInvalidRequest)
	}

	var object map[string]json.RawMessage
	if err := json.Unmarshal(request, &object); err != nil {
		return nil, fmt.Errorf("%w: decode request: %w",
			ErrQueryInvalidRequest, err)
	}
	if object == nil {
		return nil, fmt.Errorf("%w: request must be a JSON object",
			ErrQueryInvalidRequest)
	}
	if _, exists := object["@extra"]; exists {
		return nil, fmt.Errorf("%w: request already contains @extra",
			ErrQueryInvalidRequest)
	}

	encodedID, err := json.Marshal(string(queryID))
	if err != nil {
		return nil, fmt.Errorf("%w: encode query ID: %w",
			ErrQueryInvalidRequest, err)
	}
	object["@extra"] = encodedID

	encodedRequest, err := json.Marshal(object)
	if err != nil {
		return nil, fmt.Errorf("%w: encode request: %w",
			ErrQueryInvalidRequest, err)
	}
	return RawMessage(encodedRequest), nil
}

// responseQueryID extracts a telecli QueryID from @extra.
//
// The returned boolean is true only for a string @extra in the telecli
// namespace.
//
// Missing, null, non-string, empty, and foreign @extra values are not
// owned by the query router and are reported as (zero, false, nil).
// Malformed JSON in the envelope is the only error case.
func responseQueryID(raw RawMessage) (QueryID, bool, error) {
	var envelope queryEnvelope
	if err := json.Unmarshal(raw, &envelope); err != nil {
		return "", false, fmt.Errorf("decode response envelope: %w", err)
	}
	if len(envelope.Extra) == 0 || string(envelope.Extra) == "null" {
		return "", false, nil
	}

	var value string
	if err := json.Unmarshal(envelope.Extra, &value); err != nil {
		// @extra belongs to another component or uses another JSON
		// representation. It is not a telecli query response.
		return "", false, nil
	}

	queryID := QueryID(value)
	if queryID == "" || !isTelecliQueryID(queryID) {
		return "", false, nil
	}
	return queryID, true, nil
}

// decodeQueryResult converts a raw TDLib response into either a copied
// response payload or a typed TDLibError.
func decodeQueryResult(raw RawMessage) (RawMessage, error) {
	var envelope tdlibErrorEnvelope
	if err := json.Unmarshal(raw, &envelope); err != nil {
		return nil, fmt.Errorf("decode TDLib response: %w", err)
	}
	if envelope.Type != "error" {
		return append(RawMessage(nil), raw...), nil
	}

	var extra QueryID
	if len(envelope.Extra) != 0 && string(envelope.Extra) != "null" {
		var value string
		if err := json.Unmarshal(envelope.Extra, &value); err == nil {
			extra = QueryID(value)
		}
	}

	return nil, &TDLibError{
		Code:    envelope.Code,
		Message: envelope.Message,
		Extra:   extra,
		Raw:     append(RawMessage(nil), raw...),
	}
}

// Query sends one asynchronous TDLib request and waits for the matching
// @extra response.
//
// Everything it returns carried a telecli @extra: the routing below hands
// over nothing else, so an answer a caller reads always names the request
// it belongs to.
//
// The pending registry belongs to the client rather than to this session:
// an answer is routed by the identifier on it, and the identifier is the
// only thing that says which request it belongs to. A reader that is not
// the sender must still hand the answer over, so a second session over
// the same client cannot keep the answers of the first.
func (s *AuthorizedSession) Query(
	ctx context.Context,
	request RawMessage,
) (RawMessage, error) {
	if s == nil || s.client == nil {
		return nil, ErrSessionNilClient
	}
	if s.sender == nil {
		return nil, ErrSessionNilSender
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}

	if err := s.acceptQueries(); err != nil {
		return nil, err
	}

	queryID := newQueryID(s.client.ID())

	requestWithID, err := withQueryID(request, queryID)
	if err != nil {
		return nil, err
	}

	pending := &pendingQuery{
		response: make(chan queryResult, 1),
	}

	if err := s.client.registerQuery(queryID, pending); err != nil {
		return nil, err
	}

	// Registration happens before Send. TDLib may respond immediately.
	defer s.client.unregisterQuery(queryID, pending)

	if err := s.sender.Send(s.client.ID(), requestWithID); err != nil {
		return nil, fmt.Errorf("telegram query: send: %w", err)
	}

	select {
	case result, ok := <-pending.response:
		if !ok {
			return nil, ErrQueryResponseChannelClosed
		}
		if result.err != nil {
			return nil, result.err
		}
		return decodeQueryResult(result.raw)

	case <-s.pumpDone:
		return nil, ErrQuerySessionClosed

	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

// acceptQueries reports whether this session can still wait for an
// answer.
//
// The check is separate from the registration because the registry is the
// client's: a session whose pump has stopped must not leave a waiter
// behind, and it must not disturb the waiters of another session over the
// same client. A caller that passes this check and then races with the
// pump's exit is still released, because Query waits on pumpDone too.
func (s *AuthorizedSession) acceptQueries() error {
	select {
	case <-s.pumpDone:
		return ErrQuerySessionClosed
	default:
		return nil
	}
}

// registerQuery registers a pending answer on the client.
func (c *Client) registerQuery(
	queryID QueryID,
	pending *pendingQuery,
) error {
	if c == nil || queryID == "" || pending == nil {
		return ErrQueryInvalidRequest
	}

	c.queryMu.Lock()
	defer c.queryMu.Unlock()

	if c.queryErr != nil {
		return c.queryErr
	}
	if _, exists := c.pendingQueries[queryID]; exists {
		return fmt.Errorf("telegram query: duplicate query ID %q", queryID)
	}
	if c.pendingQueries == nil {
		// A Client built by a test is a literal, so the map is made
		// here rather than by every construction site.
		c.pendingQueries = make(map[QueryID]*pendingQuery)
	}
	c.pendingQueries[queryID] = pending
	return nil
}

// unregisterQuery removes pending only when it is still the registered
// waiter for queryID.
func (c *Client) unregisterQuery(
	queryID QueryID,
	pending *pendingQuery,
) {
	c.queryMu.Lock()
	defer c.queryMu.Unlock()

	current, exists := c.pendingQueries[queryID]
	if !exists || current != pending {
		return
	}
	delete(c.pendingQueries, queryID)
}

// routeResponse routes one response read from the client.
//
// The boolean result is true only when raw contains a telecli-owned
// @extra that matched a currently pending request, or when a late
// response for an abandoned query is consumed silently.
//
// A response without a telecli-owned @extra, or with a foreign @extra
// (string or otherwise), is treated as a normal application update.
func (c *Client) routeResponse(raw RawMessage) (bool, error) {
	queryID, owned, err := responseQueryID(raw)
	if err != nil {
		return false, err
	}
	if !owned {
		return false, nil
	}

	c.queryMu.Lock()
	pending := c.pendingQueries[queryID]
	if pending != nil {
		delete(c.pendingQueries, queryID)
	}
	c.queryMu.Unlock()

	if pending == nil {
		// A late response to an abandoned telecli query is consumed
		// rather than exposed on the application update stream. No
		// waiter can be added under this identifier again, so nothing
		// can be waiting for it.
		return true, nil
	}

	pending.response <- queryResult{
		raw: append(RawMessage(nil), raw...),
	}
	return true, nil
}

// failPendingQueries resolves all pending answers with err.
//
// The runtime calls it once per client, when the client's update channel
// is closed and no reader is left. A session that stops on its own does
// not call it: another session may still be reading the same client, and
// its waiters are not this session's to fail.
func (c *Client) failPendingQueries(err error) {
	if c == nil {
		return
	}
	if err == nil {
		err = ErrQuerySessionClosed
	}

	c.queryMu.Lock()
	pending := c.pendingQueries
	c.pendingQueries = make(map[QueryID]*pendingQuery)
	c.queryErr = err
	c.queryMu.Unlock()

	for _, query := range pending {
		query.response <- queryResult{err: err}
	}
}

// unexpectedResponse names a request, the type that answered it and the
// identifier the answer carried.
//
// Only those three are read. An answer can hold a name, a phone number or
// a message body, and an error message must not carry any of it; the
// identifier is enough to find the request in a trace, and the type says
// whose answer it was.
func unexpectedResponse(requestType string, raw RawMessage) string {
	identifier := responseExtra(raw)
	if identifier == "" {
		return fmt.Sprintf(
			"%s returned @type=%q",
			requestType,
			responseTypeName(raw),
		)
	}
	return fmt.Sprintf(
		"%s returned @type=%q @extra=%q",
		requestType,
		responseTypeName(raw),
		identifier,
	)
}

// responseTypeName reads only the "@type" of a response.
func responseTypeName(raw RawMessage) string {
	var envelope struct {
		Type string `json:"@type"`
	}
	if err := json.Unmarshal(raw, &envelope); err != nil {
		return ""
	}
	return envelope.Type
}

// responseExtra reads only the "@extra" of a response, and answers an
// empty string when there is none or it is not a string.
//
// The identifier is generated by newQueryID and copied by TDLib, so it
// carries nothing that came off the wire.
func responseExtra(raw RawMessage) string {
	var envelope queryEnvelope
	if err := json.Unmarshal(raw, &envelope); err != nil {
		return ""
	}
	if len(envelope.Extra) == 0 || string(envelope.Extra) == "null" {
		return ""
	}
	var value string
	if err := json.Unmarshal(envelope.Extra, &value); err != nil {
		return ""
	}
	return value
}
